### ISSUE TITLE
ZeroDivisionError가 컴파일에러가 아닌 런타임에러로 처리됩니다.

### ISSUE THREAD

**Issue by wonjinYi** [riroan/lollang#2]
# 요약
ZeroDivisionError가 컴파일에러가 아닌 런타임에러로서 발생합니다.

# 의문
zero division을 lollang에서 컴파일에러로 처리하기를 원하시는지 궁금합니다.
(이 에러를 컴파일단에서 검사하는 코드가 커밋에 누락되었는지?)

# 배경
```
우리 잘해보죠
아트록스님 캐리좀 ㅠㅏㄴㅠㅡㅠㄹ
팀차이 ㅈㅈ
```

위 코드는 ZeroDivisionError 가 발생하는 lollang코드입니다.
현재 해당 에러에 대한 처리는 ``compiler.py``의 두 곳에서 하고 있습니다.

* 380행 : def compileFile(self, path, outPath = "out.py"):
```python
except ZeroDivisionError:
            print(f"{self.currentLine}번째 적이 전장의 화신입니다!!")
```
* 392행 : def run(self, path = "out.py"):
``` python
except:
    print("소환사 한명이 게임을 종료했습니다.")
```

# 문제상황
f"{self.currentLine}번째 적이 전장의 화신입니다!!" 오류메시지가 출력될 것이 예상되었으나,
"소환사 한명이 게임을 종료했습니다." 오류메시지가 출력되었습니다.

즉, 380행 컴파일에러(except ZeroDivisionError)로는 잡지 못하고,
392행 **런타임에러(except)로 잡히는 것을 확인**하였습니다.

또한, ``compiler.py``내에서 zero division관련 에러를 발생시키는 부분을 발견하지 못했습니다.

# 맺음 : 런타임에러로 처리하는 경우
**만약 zero division을 런타임에러로 처리하기로 결정한 경우**
``compiler.py``의 367~392행을 아래와 같이 변경할 것을 건의드립니다.
``` python
def compileFile(self, path, outPath = "out.py"):
    try:
        with open(path, "r", encoding="utf-8") as file:
            codelines = [i.strip() for i in file.readlines()]
            self.compile(codelines)
    except TypeError:
        print(f"{self.currentLine}번째 적이 학살중입니다!!")
    except SyntaxError:
        print(f"{self.currentLine}번째 적은 전설적입니다!!")
    except ValueError:
        print(f"{self.currentLine}번째 적을 도저히 막을 수 없습니다!!")
    except KeyError:
        print(f"{self.currentLine}번째 적이 전장을 지배하고 있습니다!!")
    except FileNotFoundError:
        print("서버에 연결할 수 없습니다.")
    else:
        self.save(outPath)
        self.run(outPath)

def run(self, path = "out.py"):
    try:
        exec(open(path).read())
    except ZeroDivisionError:      ####################  ZeroDivisionError 처리 여기로 이동
            print("적이 전장의 화신입니다!!")
    except Exception as ex:
        print("소환사 한명이 게임을 종료했습니다.")
```

**Comment by riroan** [comment]
런타임에러 맞습니다.
제안하신 코드로 수정했습니다.
