### ISSUE TITLE
변수 선언 시 '님'을 띄어 쓸 수 있게 해주세요

### ISSUE THREAD

**Issue by tnraro** [riroan/lollang#3]
[국국원](https://www.korean.go.kr/front/onlineQna/onlineQnaView.do?mn_id=216&qna_seq=62269)에 따르면, 이름 뒤에 붙는 '님'은 의존 명사이므로 띄어 쓰는 것을 원칙으로 하고 있습니다.

`징크스 님`, `바이 님`, `시셀라 님 캐리좀 ㅠ`과 같은 문법을 지원해주세요.

**Comment by riroan** [comment]
언어 설계과정에서 롤 채팅과 최대한 유사하게 만들기 위해 변수명과 선언키워드 "님" 을 붙여서 사용하기로 설계했습니다.
이 부분은 롤랭 언어적 허용으로 이해해주시면 감사하겠습니다. 😄
